baseURL = "https://www.all-loops-considered.dev"
languageCode = "en-us"
title = "All Loops Considered"
theme = "hello-friend"
paginate = 5
enableRobotsTXT = true
canonifyURLs = true

[params]
  defaultTheme = "dark"
  showReadingTime = false

[languages]
  [languages.en]
    title = "All Loops Considered"
    copyright = "2020 © Martin Picard"
    keywords = "software development agile management tech technology code coding"

    [languages.en.params.logo]
      logoText = "All Loops Considered"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
